- BE/app.js
- FE/src/App.js
- FE/src/pages/Home.js
> [hyeok][fix] Front-End App.js Router 수정

- FE/src/components/LandingPage.js
- FE/src/components/MapContainer.js
- FE/src/components/SearchList.js
[규][Feature search map] 지도검색 카카오맵검색 개발 완료
> [규][Feature search map] 지도검색 카카오맵검색까지만 개발

- BE/app.js
- BE/package.json
> [hyeok][fix] BE 주석 제거

- FE/src/components/auth/Auth.js
- FE/src/pages/Home.js
- FE/src/pages/sign/SignIn.js
RequireAuth 로그인해도 search page 접근 못하는 에러 수정
+
app.js 충돌 해결 후 푸시
> [hyeok][fix] RequireAuth error resolve + conflict resolve

- BE/app.js
- BE/models/Project.js
- FE/src/App.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/shareMemo/TextEditor.js
> [수연][share-memo] Implement share-memo in project page with ObjectID

- FE/.env
- FE/src/components/CreateProject.js
- FE/src/components/auth/Auth.js
- FE/src/components/searchMap/SearchList.js
- FE/src/components/sign/KakaoSignIn.js
- FE/src/components/voiceTalk/sessionFunc.js
- FE/src/pages/shareMemo/TextEditor.js
- FE/src/pages/sign/SignIn.js
- FE/src/pages/sign/SignUp.js
- FE/src/setupProxy.js
FE/.env 확인하여 
REACT_APP_SERVER_IP=localhost  (로컬)
REACT_APP_SERVER_IP=서버_ip (서버)
세팅하시고 서버와 API 통신을 하실 때 process.env.REACT_APP_SERVER_IP 변수로 요청하세요
> [Feature voice talk] [front fetch cors 피하기 위해 .env파일 내에 REACT_APP_SERVER_IP 변수 추가]

- BE/routes/users/users.js
- FE/src/components/auth/Auth.js
- FE/src/pages/Home.js
- FE/src/pages/sign/SignIn.js
- FE/src/pages/sign/SignUp.js
> [hyeok][주석제거] 주석제거 for bro.뀨~

- FE/src/components/auth/Auth.js
- FE/src/pages/sign/SignUp.js
> [hyeok][주석제거] 주석제거 for bro.뀨~.~

- FE/src/components/searchMap/MapContainer.js
- FE/src/components/searchMap/SearchBar.js
- FE/src/components/searchMap/SearchList.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/search/Search.js
[허원영][Feature project page] 검색페이지 css 수정
> [허원영][Feature project page] css 수정

- FE/src/components/spot/SpotList.js
- FE/src/pages/spotRoute/SpotRoute.js
[hyeok][feat] SpotRoute LayOut Update
text editor는 수연님이 고치는 거로
> [hyeok][feat] SpotRoute LayOut Update

- FE/src/components/spot/SpotList.js
- FE/src/pages/shareMemo/TextEditor.js
- FE/src/pages/spotRoute/SpotRoute.js
[hyeok][fix] SpotRoute CSS Update
> [hyeok][fix] SpotRoute CSS Update

- FE/src/components/sign/KakaoSignIn.js
kakaoSignin.js에 credentials 추가하여 쿠키에 토큰 정상 저장
> [영지][카카오 로그인] kakaoSignin.js credentials 추가

- BE/routes/projects/projects.js
- FE/src/components/searchMap/SearchBar.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/src/components/sidebar/ProjectSide.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/shareMemo/TextEditor.js
- FE/src/pages/spotRoute/SpotRoute.js
[허원영][feature-project-fix] 서버와 연동
> [허원영][feature-project-fix] 서버와 연동

- FE/src/components/MarkMap/MarkMap.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/spot/SpotList.js
- FE/yarn.lock
> [허원영][project-fix] css 수정

- BE/routes/projects/projects.js
- FE/src/components/searchMap/SearchListRoute.js
- FE/src/components/sidebar/PlanList.js
- FE/src/pages/sign/SignIn.js
> [Feature project fix] 버그 fix

- FE/src/components/MarkMap/MarkMap.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/spot/SpotList.js
- FE/src/pages/sign/SignIn.js
[[허원영][bug fix] 세부정보 경로페이지 경로 삭제 bug fix]
> [허원영][Feature project fix]

- FE/src/components/sidebar/ProjectSide.js
[hyeok][fix] ProjectSide.js Error fix ver 2
> [hyeok][fix] ProjectSide.js Error fix

- BE/routes/projects/projects.js
- FE/src/components/searchMap/SearchListRoute.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/src/components/spot/SpotList.js
- FE/src/index.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/search/Search.js
- FE/src/pages/spotRoute/SpotRoute.js
경로 삭제 시 반영되게 구현
경로 저장 이벤트 됐다 안됐다 하던 bug fix 
-> 비동기 처리 문제로 인하여 문제 발생
해결: async await으로 비동기 문제 해결 후 정상 동작
> [허원영][shared-editing] 경로 Patch 이벤트 됐다 안됐다하던 bug fix

- FE/src/App.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/shareMemo/TextEditor.js
- FE/src/pages/spotRoute/SpotRoute.js
- 같은 날짜별 상세페이지를 보고있는 사용자들만 메모 & 커서 & 마우스 포인터가 공유되도록 수정했습니다.
- 다른 날짜, 혹은 다시 검색하러 가면 공유 커서와 포인터가 삭제됩니다.
- 동시에 ProjectId와 tripDate를 모두 props로 넘겨 처리했습니다.
> [수연][fix] 날짜별로 share-memo & cursor 따로 공유되도록 수정

- FE/src/atomics/FriendInvite.js
- FE/src/components/CreateProject.js
[hyeok][fix] 
친구 초대장에서 파티장 이름 안나오는 에러 수정
여행 계획 당일로 만들었는데 2일로 나오는 에러 수정
> [hyeok][fix] 친구 초대장에서 파티장 이름 안나오는 에러 수정, 여행 계획 당일로 만들었는데 2일로 나오는 에러 수정

- BE/routes/projects/projects.js
[hyeok][fix] 여행계획 당일로 만들었는데 2일로 만들어지는 오류 해결 ver 2
> [hyeok][fix] 여행계획 당일로 만들었는데 2일로 만들어지는 오류 해결 ver 2

- BE/models/User.js
- BE/routes/users/users.js
- FE/src/atomics/ProfileDetail.js
- FE/src/components/MarkMap/MarkMap.js
- FE/src/components/auth/Auth.js
- FE/src/components/sidebar/ProjectSide.js
- FE/src/pages/sign/SignIn.js
- FE/src/pages/sign/SignUp.js
[hyeok][fix] 
SignIn 예외처리 + 로그아웃 팝오버 UI Update
Sign 예외처리 + UX Update
> [hyeok][fix] SignIn 예외처리 + 로그아웃 팝오버 UI Update

- BE/app.js
- FE/src/atomics/FriendInvite.js
- FE/src/components/MarkMap/MarkMap.js
- FE/src/components/searchMap/SearchListRoute.js
- FE/src/components/sidebar/Footer.js
- FE/src/pages/shareMemo/MousePointer.jsx
- FE/src/pages/shareMemo/TextEditor.js
- FE/src/pages/shareMemo/TextEditorUsers.jsx
- FE/src/pages/sign/SignIn.js
[[허원영][feature-shared-editing] 먼저 접속한 유저 팅기는 버그fix, 마우스 커서 깜빡이는 버그 fix]
> [허원영][feature-shared-editing] 먼저 접속한 유저 팅기는 버그fix, 마우스 커서 깜빡이는 버그 fix

- FE/src/components/CreateProject.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/src/components/spot/SpotList.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/spotRoute/SpotRoute.js
변경 함수에서 selectedIndex를 추가하여 수정 시 정확한 위치 반영
> [허원영][cursor-debug] spotlist 이동시 planList 첫날 바뀌는 버그 fix

- BE/package-lock.json
- BE/package.json
- BE/routes/travel/travel.js
- BE/yarn.lock
- FE/src/App.js
- FE/src/components/spot/SpotDetail.js
- FE/src/pages/search/Search.js
- FE/yarn.lock
지도 항목 클릭시 카카오 페이지에서 후기 크롤링
크롤링 데이터 늘릴예정~
> [영지][지도 상세페이지] 크롤링 서버통시 구현

- FE/src/atomics/FriendProfile.js
- FE/src/components/searchMap/Drawer.css
- FE/src/components/searchMap/SearchBar.js
- FE/src/components/searchMap/SearchDetail.js
- FE/src/components/searchMap/SearchListRoute.js
- FE/src/components/sidebar/Footer.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/src/pages/search/Search.js
[hyeok][fix] 
Search Page CSS Update
상세페이지 Drawer 추가
> [hyeok][fix] Search Page CSS Update + 상세페이지 Drawer

- BE/app.js
- BE/yarn.lock
- FE/src/App.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/shareMemo/TextEditor.js
- FE/src/pages/shareMemo/TextEditorUsers.jsx
- [bug 1] text가 날짜별로 공유되지 않는 문제 → trip_date+projectID 값을 connection key로 변경했습니다.
- [bug 2] trip_date를 project_id와 동시에 param으로 넘기면 중복 라우팅되던 문제 → isFirstPage 플래그를 복구해 해결했습니다.
- [bug 3] 커서와 마우스 포인터가 실제로는 삭제되지 않아서 text가 중복으로 입력되는 문제
→ yjs + quill + quill-cursors 로 갈아타보려고 했으나 quill-cursors는 mouse pointer를 지원하지 않아 rollback 했습니다.
(아붕이에서 여러 사용자 접속 시 느려졌던 문제는 제 맥붕이에서 나타나지 않았습니다.)
> [수연][fix] share-memo 날짜별 공유 복구, trip_date 동시에 param 주면 중복라우팅되는 문제 해결

- BE/app.js
- BE/yarn.lock
- FE/src/App.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/shareMemo/TextEditor.js
- FE/src/pages/shareMemo/TextEditorUsers.jsx
- FE/src/pages/spotRoute/SpotRoute.js
> Revert "[수연][fix] share-memo 날짜별 공유 복구, trip_date 동시에 param 주면 중복라우팅되는 문제 해결"

- BE/app.js
- BE/yarn.lock
- FE/package-lock.json
- FE/src/components/spot/SpotList.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/shareMemo/TextEditor.js
- FE/yarn.lock
[[허원영][shared memo] 여러 글자 동시에 나오는 버그 fix]
동시에 입력되는 글자 meta 데이터의 ts값으로 필터처리
> [허원영][shared memo] 여러 글자 동시에 나오는 버그 fix

- FE/package-lock.json
- FE/src/components/searchMap/SearchListRoute.js
- FE/src/components/sidebar/Footer.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/src/components/spot/SpotList.js
- FE/src/components/voiceTalk/NewAudio.js
- FE/src/pages/shareMemo/TextEditor.js
- FE/src/pages/shareMemo/TextEditorUsers.jsx
- FE/yarn.lock
[[허원영][cursor-debug] 마우스 커서 나타나는 부분 수정](https://github.com/Suyeon-B/Nolmungshimung/commit/e70c703e0b53aa2b5cb6e9cd7ba2b0fc953536df)
> [허원영][cursor-debug] 마우스 커서 나타나는 부분 수정

- BE/app.js
- FE/src/pages/shareMemo/TextEditor.js
- FE/yarn.lock
- cors -> https 설정 추가 후 로컬환경 테스트 통과했습니다.
> [수연][share-memo-https] local test passed

- FE/src/components/shareMemo/MemoRtc.js
- FE/src/pages/spotRoute/SpotRoute.js
projectID가 같은 방이 있으면 새로 생성하지 않도록 예외처리 남음
> [수연][share-memo-reractoring] userID & color 반영

- FE/package-lock.json
- FE/src/components/searchMap/SearchListRoute.js
- FE/src/components/shareMemo/MemoRtc.js
- FE/src/components/sidebar/Footer.js
- FE/src/components/sidebar/PlanList.js
- FE/src/pages/shareMemo/Cursor.js
- FE/src/pages/spotRoute/SpotRoute.js
- FE/yarn.lock
[[허원영]css 수정](https://github.com/Suyeon-B/Nolmungshimung/commit/63a808e79a846bd65d66104385b0a1ad7a0ca2bd)
> [허원영]css 수정

- BE/app.js
- FE/src/components/sidebar/PlanList.js
> [허원영]생성 이벤트 추가

- BE/app.js
- BE/package-lock.json
- BE/yarn.lock
- FE/src/atomics/FriendInvite.js
- FE/src/atomics/FriendProfile.js
- FE/src/components/sidebar/Footer.js
- FE/src/components/sidebar/PlanList.js
- FE/src/pages/Home.js
- FE/src/pages/HomeNew.js
커서 색상이 같은 색으로 고정되던 버그 fix
보이스톡의 접속 인원이 새로고침 후 사라지던 버그 fix
> [허원영][debugging] 커서 색상 및 보이스톡 접속 인원 bug fix

- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
[hyeok][fix] 
검색페이지에서 날짜 눌렀는데 상세페이지 안가지는 BUG FIX
> [hyeok][fix] 검색페이지에서 날짜 눌렀는데 상세페이지 안가지는 BUG FIX

- FE/src/components/sidebar/Footer.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/spot/SpotList.js
- FE/src/pages/spotRoute/SpotRoute.js
> hyeok][fix] CSS Update

- BE/app.js
- FE/package-lock.json
- FE/src/components/sidebar/Footer.js
- FE/src/pages/HomeItems.js
- FE/src/pages/ProjectList.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/shareMemo/Cursor.js
- FE/src/pages/spotRoute/SpotRoute.js
- FE/yarn.lock
서버에서 정해주던 user color값을 각 클라이언트가 정하게 수정
> [허원영][user-color] color값 클라이언트에서 정하게 변경

- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/src/pages/spotRoute/SpotRoute.js
[허원영][css 수정] 상세페이지 css 수정
프로젝트 타이틀 home icon 수정
> [허원영][css 수정] 상세페이지 css 수정

- BE/package-lock.json
- BE/yarn.lock
- FE/src/components/MarkMap/resultMap.js
- FE/src/components/sidebar/Footer.js
- FE/src/components/voiceTalk/voiceTalk.js
- FE/src/pages/Result.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/spotRoute/SpotRoute.js
- FE/yarn.lock
[hyeok][feat] 
result page combine
> [hyeok][feat] result page combine

- FE/src/components/voiceTalk/voiceTalk.js
- FE/src/pages/project/ProjectPage.js
[hyeok][fix] 
voice login check : session -> auth CHANGE ver.2
> [hyeok][fix] voice login check : session -> auth CHANGE ver.2

- FE/src/components/MarkMap/MarkMap.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/spotRoute/SpotRoute.js
[hyeok][fix] 
when plan side bar route delete, map not update bug fix
플랜사이드바 여행지 삭제시 맵에 반영안되는 버그 픽스
> [hyeok][fix] when plan side bar route delete, map not update bug fix

- BE/app.js
- FE/src/App.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/shareMemo/Cursor.js
- FE/src/socket.js
[허원영][feature-socket] 나간유저 socket leave
> [허원영][feature-socket] 나간유저 socket leave

- FE/src/App.js
- FE/src/components/auth/Auth.js
- FE/src/components/searchMap/SearchBar.js
[hyeok][fix] 
User Auth Authorization FIX
> [hyeok][fix] User Auth Authorization FIX

- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/src/components/spot/SpotList.js
- FE/src/pages/Result.js
- FE/src/pages/project/ProjectPage.js
[hyeok][fix]
Plan List + Spot List Bug FIX
> [hyeok][fix] Plan List + Spot List Bug FIX

- FE/src/pages/ProjectList.js
[[허원영][project-delete] delete css 추가
> Feature project delete

- FE/src/pages/search/Search.js
[hyeok][fix] 
지도 핀누르면 이동안하는 버그 픽스...ㅎㅎ
> [hyeok][fix] 지도 핀누르면 이동안하는 버그 픽스...ㅎㅎ

- BE/.gitignore
- BE/app.js
- BE/routes/projects/projects.js
- BE/routes/recommend/recommend.js
- BE/routes/users/users.js
- BE/yarn.lock
- FE/src/components/shareMemo/MemoRtc.js
- FE/src/pages/recommend/RecommendPage.js
- @wnsrb003 API 작업 필요하시면 `BE/routes/recommend/recommend.js` 에서 하시면 됩니다.
- uploadedPage fetch 잘 되는 것을 확인했습니다.
> [수연][recommendPage] BE route & API setting

- BE/routes/recommend/recommend.js
- FE/src/App.js
- FE/src/pages/recommend/RecommendPage.js
- FE/src/pages/recommend/RecommendPageDetail.js
아직 구현되지 않은 부분
https://user-images.githubusercontent.com/78828589/180641269-a3c1b6c6-4ccf-4c1c-ac12-a06cfe7e7d85.mov
> [수연][recommendPage] uploadedPage data 반영, detail 페이지 연결

- BE/routes/recommend/recommend.js
- FE/src/pages/recommend/RecommendPageDetail.js
- @wonyoung2257 `FE/src/pages/recommend/RecommendPageDetail.js` 에서 가져오기 작업 해주시면 될 것 같습니다.
> [수연][recommendPage] recommendPage -> 클릭 시 detail 페이지 구현 완료

- FE/src/components/CreateProject.js
- FE/src/components/searchMap/SearchListRoute.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/src/components/sidebar/ProjectSide.js
- FE/src/pages/HomeItems.js
- FE/src/pages/HomeMain.js
- FE/src/pages/HomeNew.js
- FE/src/pages/ProjectList.js
- FE/src/pages/recommend/RecommendPage.js
- FE/src/pages/sign/SignIn.js
- FE/src/pages/sign/SignUp.js
> [수연][recommendPage] Home -> recommendPage btn 구현

- BE/routes/projects/projects.js
- FE/src/pages/result/Result.js
[hyeok][fix] 
hash table id : projectID -> UploadProjectID chagne 
result page CSS Update
> [hyeok][fix] hash table id : projectID -> UploadProjectID chagne + result page CSS Update"

- BE/routes/projects/projects.js
- FE/src/components/recommendModal/GetProjectModal.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/yarn.lock
[허원영][getproject-recommend] 여행제목 및 날짜 선택 예외처리
여행 제목 및 날짜 미 입력시 alert창으로 경로
> [허원영][getproject-recommend] 여행제목 및 날짜 선택 예외처리

- FE/src/atomics/ButtonGo.js
- FE/src/atomics/FriendInvite.js
- FE/src/atomics/FriendProfile.js
- FE/src/atomics/SideBarTitle.js
- FE/src/components/MarkMap/resultMap.js
- FE/src/components/searchMap/SearchBar.js
- FE/src/components/searchMap/SearchDetail.js
- FE/src/components/searchMap/SearchListRoute.js
- FE/src/components/shareMemo/MemoRtc.js
- FE/src/components/sidebar/Footer.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/src/components/spot/SpotList.js
- FE/src/components/spot/SpotRouteTitle.js
- FE/src/components/voiceTalk/voiceTalk.js
- FE/src/pages/HomeNew.js
- FE/src/pages/ProjectList.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/result/Result.js
- FE/src/pages/result/ResultModal.js
- FE/src/pages/search/Search.js
- FE/src/pages/shareMemo/Cursor.js
- FE/src/pages/spotRoute/SpotRoute.js
[hyeok][refactor]
front React.memo 
useCallback 
Componentilization
상세보기 사진 여러개 autoplay 기능 추가
++ 수정 예정 사항
Drag Start, End할때 전체가 재렌더링 되는 문제 -> 작게 컴포넌트화하면 안되는걸 확인 -> 잘게 컴포넌트화 하자
검색, 여행지 추가, 핀 누를때 search가 재렌더링 되는 부분 수정 필요
window.location.href -> navigate로 변경 !
> [hyeok][refactor] front React.memo + useCallback + Componentilization

- FE/src/components/shareMemo/MemoRtc.js
[hyeok][fix] memo RTC Session -> Auth
> [hyeok][fix] memo RTC Session -> Auth  

- FE/src/components/shareMemo/MemoRtc.js
[hyeok][fix] memo RTC Session -> Auth ver.2
> [hyeok][fix] memo RTC Session -> Auth ver.2

- FE/src/components/searchMap/SearchListRoute.js
[[허원영] search-drop-down z-index 수정]
> [허원영] search-drop-down z-index 수정

- FE/src/components/CreateProject.js
[hyeok][fix] 
Navigate Update : window.location -> navigate change
> [hyeok][fix] Navigate Update : window.location -> navigate change

- BE/routes/util/redis.js
- FE/src/pages/recommend/RecommendPage.js
- FE/src/pages/result/Result.js
- 사용자가 hashtag 없이 업로드 시 예외처리
- 대표 img 없는 프로젝트 업로드 시 예외처리
> [수연][recommendPage] hashtag, img bug fix

- FE/src/pages/HomeMain.js
- FE/src/pages/recommend/RecommendPage.js
- FE/src/pages/result/Result.js
[[허원영][css] recommand page css 수정](https://github.com/Suyeon-B/Nolmungshimung/commit/25246bcc2fd04a37b79a7174b1df1332dacdf6ae)
> [허원영][css] recommand page css 수정

- FE/src/App.js
- FE/src/components/searchMap/SearchListRoute.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/spotRoute/SpotRoute.js
[hyeok][refactor] 
Lazy Loading Function ADD without recommand page
> [hyeok][refactor] Lazy Loading Function ADD without recommand page

- FE/src/components/recommend/RecommendRows.js
- FE/src/pages/recommend/RecommendPage.js
- FE/src/pages/result/Result.js
- result page의 메모는 임시로 주석처리했습니다.
- infinite scroll은 스크롤 부분을 컴포넌트화하여 lazy load하도록 변경했습니다.
> [수연][infinite & result memo] lazy-load & memo 주석

- BE/routes/projects/projects.js
- FE/src/atomics/Badge.js
- FE/src/components/CreateProject.js
- FE/src/components/invite/InviteProject.js
- FE/src/components/recommendModal/GetProjectModal.js
- FE/src/components/sign/KakaoSignIn.js
- FE/src/pages/project/ProjectPage.js
- FE/src/pages/project/Sfu.js
- FE/src/pages/result/Result.js
- FE/src/pages/search/Search.js
- FE/src/pages/sign/SignIn.js
- FE/src/pages/sign/SignUp.js
[hyeok][refactor] 
Remove Add EVENT Listener 
Badge(Custom Alert) Componentize
: alert -> Badge Change
> [hyeok][refactor] Remove Add EVENT Listener + Badge(Custom Alert) & alert -> Badge Change

- FE/src/components/MarkMap/resultMap.js
- FE/src/components/spot/SpotList.js
- FE/src/pages/result/Result.js
[허원영][result-page-css] 결과 페이지 css 수정
색상 값 추가 및 경로 색상 날짜 별로 랜덤하게 표시
> [허원영][result-page-css] 결과 페이지 css 수정

- FE/src/components/recommend/RecommendRows.js
- FE/src/components/spot/SpotRouteTitle.js
- FE/src/pages/HomeItems.js
- FE/src/pages/HomeMain.js
- FE/src/pages/ProjectList.js
- FE/src/pages/recommend/RecommendPage.js
- FE/src/pages/result/Result.js
> [허원영][css 수정]

- FE/src/components/spot/SpotRouteTitle.js
[[허원영][feature-css] attention button css] 클릭 느낌 추가
> [허원영][feature-css] attention button css

- FE/public/index.html
- FE/src/atomics/FriendInvite.js
- FE/src/components/searchMap/SearchBar.js
- FE/src/components/spot/SpotRouteTitle.js
- FE/src/pages/sign/SignUp.js
[hyeok][fix] 
Manifest: Line: 1, column: 1, Syntax error. 
Search Bar 검색시 검색어 안없어지게 FIX
> [hyeok][fix] Manifest: Line: 1, column: 1, Syntax error. Search Bar 검색시 검색어 안없어지게 FIX

- FE/src/components/MarkMap/resultMap.js
- FE/src/pages/result/Result.js
[허원영][bug-fix] 추천 경로 페이지 오류 수정
props로 넘어오는 color값 문제 발생
> [허원영][bug-fix] 추천 경로 오류 수정

- FE/src/atomics/MapSearchBtn.js
- FE/src/components/MarkMap/resultMap.js
- FE/src/pages/recommend/RecommendPageDetail.js
- FE/src/pages/result/Result.js
- FE/src/pages/search/Search.js
[[허원영][resultMap] circle 색상 같게 변경 & 지도의 버튼 센터 맞춤]
> [허원영][resultMap] circle 색상 같게 변경 & 지도의 버튼 센터 맞춤

- BE/routes/projects/projects.js
- FE/src/components/recommendModal/GetProjectModal.js
- FE/src/components/shareMemo/MemoRtc.js
- FE/src/pages/ProjectList.js
[[허원영][cursor]cursor 이름 항시 표시] 커서의 이름 항상 표시되도록 css 수정
> [허원영][cursor]cursor 이름 항시 표시

- FE/src/components/shareMemo/MemoRtc.js
- FE/src/pages/result/Result.js
- FE/src/pages/result/ResultMemo.js
- style 적용 미반영 bug fix
- 결과 페이지에 메모결과 넣었습니다
> [수연][sharememo-refactoring] Implement memo in result page

- BE/middleware/auth.js
- BE/models/User.js
- FE/src/pages/sign/SignUpForm.js
[hyeok][fix] 
회원가입 예외처리 
Auth log
> [hyeok][fix] 회원가입 예외처리 Auth log

- BE/app.js
- BE/routes/projects/projects.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/spot/SpotList.js
- FE/src/pages/project/ProjectPage.js
- FE/yarn.lock
드래그 이벤트 시 위치변경이 되지 않았을 때 lock이 풀리지 않던 bug fix
> [허원영][bug-fix] 드래그 bug fix

- FE/src/components/sidebar/PlanList.js
- FE/src/components/sidebar/PlanSideBar.js
- FE/src/pages/project/ProjectPage.js
[[허원영][drag-fix] drag 이벤트시 fetch 2번 일어나던 동작 수정]
> [허원영][drag-fix] drag 이벤트시 fetch 2번 일어나던 동작 수정

- BE/routes/util/redis.js
- FE/src/pages/project/ProjectPage.js
> [허원영]redis env 추가

- BE/middleware/auth.js
- BE/routes/users/users.js
> [hyeok][fix] Auth ver. 7.5

- BE/app.js
- BE/routes/users/users.js
> [hyeok][fix] Auth ver. 7.6

- BE/routes/users/users.js
> [hyeok][fix] Auth ver. 7.65

- BE/routes/users/users.js
> [hyeok][fix] Auth ver. 7.69

- BE/app.js
- BE/middleware/auth.js
- BE/package-lock.json
- BE/package.json
- BE/routes/users/users.js
- BE/yarn.lock
> [hyeok][fix] Auth ver. 7.9

- FE/package-lock.json
- FE/package.json
- FE/src/App.js
- FE/src/Test.js
- FE/src/components/loading/Loading.js
- FE/src/pages/project/ProjectPage.js
- FE/yarn.lock
[허원영][Feature loading] loading 화면 추가
> [허원영][Feature loading] loading 화면

- BE/routes/users/users.js
- FE/src/components/auth/Auth.js
- FE/src/pages/HomeNew.js
- FE/src/pages/sign/SignIn.js
> [hyeok][fix] Auth ver. 8

- BE/middleware/auth.js
- BE/routes/users/users.js
- FE/yarn.lock
> [hyeok][fix] Auth ver. 8 LAST

- FE/src/App.js
- FE/src/routes.js
[[허원영][refactoring] app.js 코드 개선] routes 코드 개선
> [허원영][refactoring] app.js 코드 개선

- BE/yarn.lock
- FE/src/components/recommend/InfiniteScroll.js
- FE/src/components/recommend/ScrollRow.js
- FE/src/pages/recommend/RecommendPage.js
- 해시태그 검색 창에서 모두 삭제 시 main recommend 스크롤 나타나도록 수정
- 없는 hashtag 검색 시 예외처리
> [수연][infinite-refactoring] HashTag 검색 모두 삭제 & hashtag 검색 예외처리

- FE/src/pages/recommend/RecommendPage.js
- FE/yarn.lock
- 아무 것도 입력하지 않고 돋보기 클릭 시 /recommend호출 -> recommend page 메인으로 변함없도록 수정했습니다.
- 엔터 시 검색 바로 반영안되고 두번 엔터쳐야 나오는 버그 남아있습니다.
(이전 state여서 문제됩니다.)
> [수연][infinite-refactoring] HashTag 검색 버그 fix

- BE/routes/users/users.js
- FE/src/App.js
- FE/src/components/auth/Auth.js
- FE/src/pages/result/Result.js
- FE/src/pages/result/ResultModal.js
- FE/src/pages/sign/SignIn.js
- FE/src/pages/sign/SignUp.js
- FE/src/pages/sign/SignUpForm.js
[hyeok][fix] 
Auth ver.8 Real Last
App, result refactor
Signin refactor
signup refactor
> [hyeok][fix] Auth ver.8 Real Last + App, result refactor + Signin refactor

- BE/models/User.js
> [hyeok][fix] Auth Ver. 8.1

- BE/models/User.js
- FE/src/pages/result/Result.js
> [hyeok][fix] Auth Ver. 8.2

- FE/src/pages/recommend/RecommendPage.js
> [수연][infinite-refactoring] HashTag 엔터검색 바로 반영-버그 fix

- BE/models/User.js
> [hyeok][fix] Auth Ver. 8.4

- BE/routes/util/inviteMail.html
- BE/routes/util/mail.js
- BE/routes/util/redis.js
- FE/src/atomics/FriendInvite.js
[hyeok][fix] 
G 메일 중앙정렬
자기 자신 초대되는 버그 FIX
> [hyeok][fix] G 메일 중앙정렬 + 자기 자신 초대되는 버그 FIX

- BE/routes/util/redis.js
- FE/src/atomics/DetailBtn.js
- FE/src/atomics/MapSearchBtn.js
- FE/src/atomics/SearchBtn.js
- FE/src/components/CreateProject.js
- FE/src/components/recommendModal/GetProjectModal.js
- FE/src/components/sidebar/PlanBtns.js
- FE/src/components/spot/SpotRouteTitle.js
- FE/src/pages/HomeItems.js
- FE/src/pages/HomeMain.js
- FE/src/pages/ProjectList.js
- FE/src/pages/result/Result.js
[[허원영][feature-button-event]
모든 버튼 클릭 효과 추가
> [허원영][feature-button-event] 버튼 클릭 효과 추가

- FE/src/atomics/FriendInvite.js
- FE/src/pages/result/ResultModal.js
- FE/src/pages/search/Search.js
[hyeok][fix] 
invite autofocus 
pagination fix 
hashtag fix
> [hyeok][fix] invite autofocus + pagination fix + hashtag fix

- BE/routes/projects/projects.js
- FE/src/components/searchMap/SearchListRoute.js
- FE/src/components/sidebar/PlanList.js
[[허원영][lock] lock bug fix] lock이 걸린 상태에서 다른유저의 dragEnd 이벤트 발생으로 DB에 lock이 걸린 상태로 저장되던 버그 수정
> [허원영][lock] lock bug fix

- BE/routes/projects/projects.js
- FE/src/atomics/SideBarTitle.js
- FE/src/components/projectModal/ModifyModal.js
[[허원영][feature-project-modify] 프로젝트 제목 및 시작 날짜 수정
프로젝트 제목과 시작 날짜를 바탕으로 현재 프로젝트 수정
> [허원영][feature-project-modify] 프로젝트 제목 및 시작날짜 수정

- FE/src/atomics/CommonBtn.js
- FE/src/atomics/FriendInvite.js
- FE/src/components/projectModal/ModifyModal.js
- FE/src/components/searchMap/SearchListRoute.js
- FE/src/components/sidebar/Footer.js
[hyeok][fix] 
friends invite conflicts resolve 
CommonBtn hover develop
> [hyeok][fix] friends invite conflicts resolve, CommonBtn hover develop

- FE/src/components/sidebar/PlanList.js
- FE/src/components/spot/SpotList.js
[hyeok][fix] 
Drag End -- if not exist destination case error resolve
> [hyeok][fix] Drag End -- if not exist destination case error resolve

- FE/src/components/searchMap/SearchListRoute.js
- FE/src/pages/search/Search.js
[[허원영][feature-search-css] search-page-css 수정]
지도에 버튼 추가, 검색 상세보기 css 디자인 변경
> [허원영][feature-search-css] search-page-css 수정

- FE/src/components/CreateProject.js
- FE/src/components/projectModal/ModifyModal.js
- FE/src/components/searchMap/SearchDetail.js
[hyeok][css] 
search detail page css update
> [hyeok][css] search detail page css update

- FE/src/pages/project/ProjectPage.js
- FE/src/pages/shareMemo/Cursor.js
[[허원영][cursor-color-fix] color값 버그 수정함](https://github.com/Suyeon-B/Nolmungshimung/commit/1cc94728dc34c34218dce87403c401f1fa59d696)
> [허원영][cursor-color-fix] color값 버그 수정함

- FE/src/components/CreateProject.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/spot/SpotList.js
- FE/src/pages/HomeNew.js
- spot route의 border line이 보이는 css 수정
- create page의 logo 수정
> [수연][css] 디테일 수정

- FE/src/components/shareMemo/MemoRtc.js
- toolbar 부분에 반영되지 않은 css 추가했습니다.
> [수연][feature-sharememo-refactoring] quill-toolbar 수정

- BE/app.js
- FE/src/pages/project/ProjectPage.js
[[허원영][feature-user-color] color 색상 서버에서 관리]
클라이언트에서 접속한 유저의 색상 부여를 서버로 이동시킴
> [허원영][feature-user-color] color 색상 서버에서 관리

- FE/src/components/sidebar/PlanList.js
- FE/src/components/spot/SpotList.js
[hyeok][hotfix] drag start hot fix
> [hyeok][hotfix] drag start hot fix

- FE/src/components/searchMap/SearchDetail.js
- FE/src/components/sidebar/PlanList.js
- FE/src/components/spot/SpotList.js
> [허원영][lock-bug-fix]

- FE/src/components/sidebar/PlanList.js
- FE/src/components/spot/SpotList.js
> [허원영][lock-bug-fix] rollback

- FE/src/components/recommendModal/GetProjectModal.js
- FE/src/pages/recommend/RecommendPageDetail.js
[hyuk][css] 
recommend detail page css update
> [hyuk][css] recommend detail page css update

- BE/routes/voicetalk/voicetalk.js
- FE/public/index.html
- FE/src/atomics/SideBarTitle.js
- FE/src/components/MarkMap/MarkMap.js
- FE/src/components/MarkMap/resultMap.js
- FE/src/components/recommendModal/GetProjectModal.js
- FE/src/components/voiceTalk/voiceTalk.js
- FE/src/pages/recommend/RecommendPageDetail.js
[hyuk]
[css] recommend detail page css update
[fix] voicetalk fix try
> [hyuk][css] recommend detail page css update, [fix] voicetalk fix try

- FE/src/components/voiceTalk/voiceTalk.js
[hyuk][conflict] 
conflict resolve
> [hyuk][conflict] conflict resolve

- FE/src/components/recommendModal/GetProjectModal.js
- FE/src/pages/recommend/RecommendPageDetail.js
[hyuk][css] 
recommned Page css update
> [hyuk][css] recommned Page css update

- BE/yarn.lock
- FE/src/atomics/FriendInvite.js
> [수연][feature-delete-friend] 친구 삭제 시 안내 창 추가
